"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://mlp-game-wiki.no
  name = mlpgame
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'mlpgame'
    langs = {
        'en': 'mlp-game-wiki.no',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
